### ISSUE TITLE
使用docker部署，之前可以上传超过1M的图片，现在传不了。

### ISSUE THREAD

**Issue by yufxxz** [besscroft/PicImpact#125]
请问是supabase的限制还是 R2的限制呢？
自己在找了一下没看到

**Comment by besscroft** [comment]
我这边暂时没法复现，您方便找找有报什么错误吗？以及尽可能的复现步骤？

**Comment by yufxxz** [comment]
## 浏览器的错误
Request Method: POST
Status Code: 413 Request Entity Too Large
##  docker 的log
<Item> with non-plain text contents is unsupported by type to select for accessibility. Please add a `textValue` prop.
Read more at https://errors.authjs.dev/#credentialssignin
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error
    at Object.u (/app/.next/server/chunks/4033.js:55:91246)
    at async u (/app/.next/server/chunks/4033.js:55:107782)
    at async c (/app/.next/server/chunks/4033.js:55:82383)
    at async o (/app/.next/server/chunks/4033.js:431:74092)
    at async s (/app/.next/server/chunks/4971.js:1:7080)
    at async /app/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rP (/app/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
    at async r9 (/app/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1139)
    at async doRender (/app/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)

**Comment by zimBlue** [comment]
我这边加了一层nginx也出现过这个问题 nginx默认文件大小1m

**Comment by zimBlue** [comment]
nginx.conf 里 http{} 里加句client_max_body_size 10m;就行了
