### ISSUE TITLE
[bug?]新建相册时报错

### ISSUE THREAD

**Issue by Chun-QiuCC** [besscroft/PicImpact#181]
新部署的相册，后端用npm run dev启动，然后前端用nginx反代 localhost:3000 ，在新建相册时发生报错，log如下

```log
TypeError: The "payload" argument must be of type object. Received null
    at frame (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/patch-error-inspect.ts:89:42)
    at getSourcemappedFrameIfPossible (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/patch-error-inspect.ts:179:32)
    at parseAndSourceMap (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/patch-error-inspect.ts:234:23)
    at exit (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/patch-error-inspect.ts:224:32)
    at apply (webpack://next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:569:32)
    at apply (webpack://next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.node.development.js:593:32)
    at log (hono/albums.ts:25:12)
    at async AppRouteRouteModule.do (webpack://next/dist/src/server/route-modules/app-route/module.ts:529:14)
    at async AppRouteRouteModule.handle (webpack://next/dist/src/server/route-modules/app-route/module.ts:658:30)
    at async doRender (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:2503:29)
    at async responseGenerator (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:3024:21)
    at async DevServer.renderToResponseWithComponentsImpl (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:3036:23)
    at async DevServer.renderPageComponent (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:3616:15)
    at async DevServer.renderToResponseImpl (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:3678:23)
    at async DevServer.pipeImpl (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:1697:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/next-server.ts:1039:6)
    at async DevServer.handleRequestImpl (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/base-server.ts:1461:8)
    at async (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/dev/next-dev-server.ts:514:13)
    at async Span.traceAsyncFn (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/trace/trace.ts:143:13)
    at async DevServer.handleRequest (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/dev/next-dev-server.ts:512:19)
    at async invokeRender (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/lib/router-server.ts:284:10)
    at async handleRequest (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/lib/router-server.ts:530:15)
    at async requestHandlerImpl (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/lib/router-server.ts:576:6)
    at async Server.requestListener (node_modules/.pnpm/next@15.0.4-canary.5_react-dom@19.0.0-rc-5c56b873-20241107_react@19.0.0-rc-5c56b873-20241107__qzbp44d4xf7hzghrmxgu6zfepy/node_modules/next/src/server/lib/start-server.ts:146:6)
  23 |     return c.json({ code: 200, message: '新增成功！' })
  24 |   } catch (e) {
> 25 |     console.log(e)
     |            ^
  26 |     return c.json({ code: 500, message: '新增失败！' })
  27 |   }
  28 | }) {
  code: 'ERR_INVALID_ARG_TYPE'
}
 POST /api/v1/albums/add 500 in 1697ms
 ⨯ Detected default export in '/flypic/flypic/PicImpact-2.0.5/app/api/[[...route]]/route.ts'. Export a named export for each HTTP method instead.
```

**Comment by besscroft** [comment]
方便发一下您的请求参数吗？打开 F12 查看。

**Comment by Chun-QiuCC** [comment]
> 方便发一下您的请求参数吗？打开 F12 查看。

你好，我发现这个bug是在路由信息中使用 - 这个字符造成的，在改为下划线后可以正常添加相册了

**Comment by Chun-QiuCC** [comment]
顺便问一下作者正确的启动方式/指令是怎么样的？我还在使用npm run dev来启动程序

**Comment by besscroft** [comment]
如果不是容器或者 Vercel 之类部署方案，而是自己部署的话，可以使用 `pnpm run build:node` 构建，然后再使用 `node server.js` 命令启动，这样性能上会比 `pnpm run dev` 要好许多。

后面我会在文档中添加上。

**Comment by besscroft** [comment]
路由的话，一般不推荐带上字符，怕库有啥地方不支持，不过我会抽空看看是怎么个情况。

**Comment by Chun-QiuCC** [comment]
> 如果不是容器或者 Vercel 之类部署方案，而是自己部署的话，可以使用 `pnpm run build:node` 构建，然后再使用 `node server.js` 命令启动，这样性能上会比 `pnpm run dev` 要好许多。
> 
> 后面我会在文档中添加上。

感谢！

**Comment by Chun-QiuCC** [comment]
> 如果不是容器或者 Vercel 之类部署方案，而是自己部署的话，可以使用 `pnpm run build:node` 构建，然后再使用 `node server.js` 命令启动，这样性能上会比 `pnpm run dev` 要好许多。
> 
> 后面我会在文档中添加上。

抱歉，我发现在build之后并不会出现server.js，但是貌似可以使用pnpm run start来启动服务端

**Comment by besscroft** [comment]
只要是能启动编译后的程序就行了，生产环境用没问题的，生产只是不推荐 `pnpm run dev` 这种方式。
