### ISSUE TITLE
docker部署之后网站打开报错，docker日志提示  初始化数据失败，您可能需要准备干净的数据表

### ISSUE THREAD

**Issue by waleraye** [besscroft/PicImpact#23]
网页显示  Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 879300834

查下了docker日期 提示 初始化数据失败，您可能需要准备干净的数据表，请联系管理员！

这个是docker的日志，能不能帮忙看看呀？另外文档里面的docker那里可以也添加上PgSQL 的容器吗？一块部署了

npm WARN exec The following package was not found and will be installed: prisma@5.14.0
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-ap-northeast-1.pooler.supabase.com:5432"

Error: Schema engine error:
FATAL: Tenant or user not found

npm notice
npm notice New minor version of npm available! 10.5.0 -> 10.8.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.0>
npm notice Run `npm install -g npm@10.8.0` to update!
npm notice
▲ Next.js 14.2.3
- Local: http://localhost:3000
- Network: http://0.0.0.0:3000

✓ Starting...
✓ Ready in 244ms
初始化数据失败，您可能需要准备干净的数据表，请联系管理员！ PrismaClientInitializationError: Error querying the database: FATAL: Tenant or user not found
at r (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:112:2493)
at async wt.transaction (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:111:12070)
at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:127:9458)
at async Module.t (/app/.next/server/instrumentation.js:1:356)
at async NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:475:17) {
clientVersion: '5.13.0',
errorCode: undefined
}
PrismaClientInitializationError:
Invalid `prisma.tags.findMany()` invocation:

Error querying the database: FATAL: Tenant or user not found
at In.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:122:7154)
at In.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:122:6188)
at In.request (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:122:5896)
at async l (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:127:11167)
at async m (/app/.next/server/chunks/3700.js:119:94)
at async j (/app/.next/server/chunks/1228.js:1:11729)
at async f (/app/.next/server/chunks/1228.js:1:11390) {
clientVersion: '5.13.0',
errorCode: undefined,
digest: '879300834'
}
PrismaClientInitializationError:
Invalid `prisma.configs.findFirst()` invocation:

**Comment by waleraye** [comment]
抱歉，是数据库连接配置错了
