### ISSUE TITLE
docker部署报错了，数据库初始化失败

### ISSUE THREAD

**Issue by liufq777** [besscroft/PicImpact#43]
初始化数据失败，您可能需要准备干净的数据表，请联系管理员！ PrismaClientInitializationError: Error querying the database: FATAL: Tenant or user not found
    at r (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:112:2493)
    at async wt.transaction (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:111:12070)
    at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:127:9458)
    at async Module.t (/app/.next/server/instrumentation.js:1:356)
    at async NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:475:17) {
  clientVersion: '5.14.0',
  errorCode: undefined
}
PrismaClientInitializationError: 
Invalid `prisma.tags.findMany()` invocation:

**Comment by besscroft** [comment]
@liufq777 您好，请仔细检查您的数据库配置，谢谢！

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
