### ISSUE TITLE
部署报错 没看懂日志问题 是否方便帮忙看一下

### ISSUE THREAD

**Issue by chuanbizhe** [besscroft/PicImpact#49]
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 4195431812

**Comment by besscroft** [comment]
@chuanbizhe 您方便在这里贴上脱敏后的后端日志吗？它可能来着 Vercel log、nodejs log 或者 docker log。

> 根据经验，部署出问题的，大概率是数据库部分没有配置好的。您可以先检查一下，有不明白的再问我。

**Comment by chuanbizhe** [comment]
> Application error: a server-side exception has occurred (see the server logs for more information). Digest: 4195431812



> Application error: a server-side exception has occurred (see the server logs for more information). Digest: 4195431812

https://github.com/besscroft/PicImpact/issues/49#issue-2333363285

**Comment by chuanbizhe** [comment]
PrismaClientKnownRequestError:
Invalid `prisma.$executeRaw()` invocatio

**Comment by chuanbizhe** [comment]
Raw query failed. Code: `42P01`. Message: `relation "public.User" does not exist`
at In.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:6877)
at In.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:6211)
at In.request (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:5919)
at async l (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:127:11167)
at async /app/.next/server/instrumentation.js:1:387
at async Proxy._transactionWithCallback (/app/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:127:9534)
at async Module.t (/app/.next/server/instrumentation.js:1:356)
at async NextNodeServer.prepareImpl (/app/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:475:17) {
code: 'P2010',
clientVersion: '5.14.0',
meta: { code: '42P01', message: 'relation "public.User" does not exist' }
}

**Comment by besscroft** [comment]
请问下您的部署方式？

**Comment by chuanbizhe** [comment]
使用的docker

**Comment by chuanbizhe** [comment]
请问能看出来哪里的问题嘛 QAQ

**Comment by besscroft** [comment]
根据日志判断，我认为是数据库没连接上，或者是数据库用户无操作权限，导致的数据库表结构和数据初始化失败。容器化部署启动时，程序会自动去初始化，您尝试先从这方向排查看看，有问题再来问俺，我尽量提供帮助。

**Comment by besscroft** [comment]
我来录制一个部署视频，稍等一会。

**Comment by chuanbizhe** [comment]
好的好的 感谢感谢

**Comment by besscroft** [comment]
https://github.com/besscroft/PicImpact/issues/50

**Comment by besscroft** [comment]
长时间未收到反馈，如您有疑问，可重新打开！
